on: push
jobs:
  printVersion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fetch tags # Required for axion-release-plugin
        run: git fetch --tags --unshallow
      - run: ./gradlew cV